# azure-pipelines.yml (Updated with CLI upgrade step)

trigger:
- none

variables:
  resourceGroupName: 'JUICT-HUB-SPOKE-PROD'
  location: 'westeurope'
  bicepTemplateFile: './main.bicep'
  bicepParameterFile: './main.bicepparam'
  azureServiceConnection: 'azure-connection'

stages:

- stage: Validate
  displayName: 'Fase 1: Valideer Bicep & Beveiliging'
  jobs:
  - job: ValidateCode
    displayName: 'Valideer Code Kwaliteit'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: AzureCLI@2
      displayName: 'Valideer Bicep syntax (bicep build)'
      inputs:
        azureSubscription: $(azureServiceConnection)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: 'az bicep build --file $(bicepTemplateFile)'
    - task: MicrosoftSecurityDevOps@1
      displayName: 'Voer Microsoft Security DevOps-analyse uit'


- stage: Test
  displayName: 'Fase 2: Test Infrastructuur (What-If met PowerShell)'
  dependsOn: Validate
  condition: succeeded()
  jobs:
  - job: WhatIfDeployment
    displayName: 'Voorbeeld van uitrol met PowerShell What-If'
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: AzurePowerShell@5
      displayName: 'Voer What-If uitrol uit met PowerShell'
      inputs:
        azureSubscription: $(azureServiceConnection)
        ScriptType: 'InlineScript'
        Inline: |
          Write-Host "Simuleren van de uitrol met PowerShell om wijzigingen te bekijken..."

          $templateParameters = @{
            "adminPassword" = "$(adminPassword)"
          }

          # Stap 1: Voer de What-If uit en sla het resultaat op in een variabele.
          $whatIfResult = Get-AzResourceGroupDeploymentWhatIfResult `
            -ResourceGroupName "$(resourceGroupName)" `
            -TemplateFile "$(bicepTemplateFile)" `
            -TemplateParameterFile "$(bicepParameterFile)" `
            -TemplateParameterObject $templateParameters

          # Stap 2: Controleer of er wijzigingen zijn en formatteer ze als JSON voor de log.
          if ($whatIfResult.Changes) {
            Write-Host "Gedetecteerde wijzigingen:"
            # De .Changes property bevat de lijst met wijzigingen.
            # ConvertTo-Json maakt het leesbaar in de pipeline log.
            # -Depth 5 zorgt ervoor dat alle details worden getoond.
            $whatIfResult.Changes | ConvertTo-Json -Depth 5 | Write-Output
          } else {
            Write-Host "What-If is succesvol uitgevoerd. Er zijn geen wijzigingen gedetecteerd."
          }

        azurePowerShellVersion: 'LatestVersion'
        pwsh: true


- stage: Deploy
  displayName: 'Fase 3: Rol Infrastructuur Uit'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - deployment: DeployInfrastructure
    displayName: 'Uitrol van Hub-en-Spoke Architectuur'
    pool:
      vmImage: 'ubuntu-latest'
    # Gebruik een 'environment' om handmatige goedkeuringen in te stellen voor productie.
    environment: 'production' 
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Rol Bicep-template uit naar Azure'
            inputs:
              azureSubscription: $(azureServiceConnection)
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Starten van de uitrol van de hub-en-spoke infrastructuur..."
                az deployment group create \
                  --name "pipeline-deployment-$(Build.BuildId)" \
                  --resource-group $(resourceGroupName) \
                  --template-file $(bicepTemplateFile) \
                  --parameters $(bicepParameterFile) \
                  --parameters adminPassword=$(adminPassword) # Geef het geheime wachtwoord door
